# Stage 0: compile angular frontend
FROM node:20-alpine3.19 as build
# Set api url
ENV SERVER_API_URL=https://admin.abofonsa.com
ENV HEALTHCONNECT_URL=https://www.abofonsa.com

RUN npm install -g npm@10.4.0

WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN npm run webpack:prod

# Stage 1: serve app with nginx server
FROM nginx:latest
COPY --from=build /app/target/classes/static/  /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
