# Stage 0: compile angular frontend
FROM node:20-alpine3.19 as build
# Set api url
ENV SERVER_API_URL=https://hc-admin.jojoaddison.net
ENV ABOFONSA_URL=https://abofonsa.jojoaddison.net

RUN npm install -g npm@8.19.3

WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN npm run webpack:build

# Stage 1: serve app with nginx server
FROM nginx:latest
COPY --from=build /app/target/classes/static/  /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
