version: '3.5'
services:
  hc-dev-patient-dashboard:
    image: hc-patient-dashboard
    container_name: hc-patient-dashboard
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './hc-patient-dashboard:/usr/src/app'
    ports:
      - 127.0.0.1:5501:80
    networks:
      - devnet

networks:
  devnet:
    external:
      name: devnet
