version: '3.5'
services:
  patientdashboard:
    image: patientdashboard:0.0.1
    container_name: patientdashboard
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './patientdashboard:/usr/src/app'
    ports:
      - 127.0.0.1:5501:80
    networks:
      - devnet

networks:
  devnet:
    external: true
    name: devnet
