# Stage 0: compile angular frontend
FROM node:16-alpine3.13 as build
# Set api url
ENV SERVER_API_URL=https://admin.abofonsa.com
ENV ABOFONSA_URL=https://www.abofonsa.com

RUN npm install -g npm@9.6.2

WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN npm run webpack:prod

# Stage 1: serve app with nginx server
FROM nginx:latest
COPY --from=build /app/target/classes/static/  /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
