version: '3.5'
services:
  br-dev-admin-dashboard:
    image: br-admin-dashboard
    container_name: bedrock-admin-dashboard
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - './bedrock-admin-dashboard:/usr/src/app'
    ports:
      - 127.0.0.1:4200:80
    networks:
      - bedrocknet

networks:
  devnet:
    external:
      name: bedrocknet
